Update google-cloudrun-docker.yml

diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -99,6 +99,13 @@ jobs:
           docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}" ./
           docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
 
+      - name: Verify Docker Image Push
+        run: |
+          if ! gcloud artifacts docker images describe "$IMAGE_NAME"; then
+            echo "Docker image $IMAGE_NAME not found. Push may have failed."
+            exit 1
+          fi
+
       # Deploy to Cloud Run
       - name: Deploy to Cloud Run
         id: deploy
@@ -107,7 +114,7 @@ jobs:
           service: ${{ env.SERVICE }}
           region: ${{ env.REGION }}
           image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
-          flags: --quiet
+          flags: --quiet --verbosity=debug
           
         env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: '1'
